# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dborgian <dborgian@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/08 16:48:21 by dborgian          #+#    #+#              #
#    Updated: 2024/05/16 12:44:15 by dborgian         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98 main.cpp Harl.cpp -o harlFilter

fclean:
	rm -f *.o
	rm harlFilter