all:
	c++ -Werror -Wextra -Wall -std=c++98  main.cpp Bureaucrat.cpp AForm.cpp ShrubberryCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp Internal.cpp -o Internal

fclean:
	rm -f *.o
	rm -f Internal