# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dborgian <dborgian@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/08 16:58:03 by dborgian          #+#    #+#              #
#    Updated: 2024/05/08 16:58:04 by dborgian         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98  main.cpp ClapTrap.cpp ScavTrap.cpp -o ScavTrap

fclean:
	rm -f *.o
	rm -f claptrap