# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dborgian <dborgian@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/08 16:59:32 by dborgian          #+#    #+#              #
#    Updated: 2024/05/08 16:59:33 by dborgian         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98  main.cpp Animal.cpp Dog.cpp Cat.cpp Brain.cpp -o Brain

fclean:
	rm -f *.o
	rm -f Brain